version: "3.9"

services:
  database:
    image: mysql
    container_name: database
    volumes:
      - ./data/database:/var/lib/mysql
    ports:
      - ${DATABASE_MAP_PORT}:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}

  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver ${BACKEND_HOST}:${BACKEND_SERVER_PORT}
    volumes: 
      - ./backend:/backend
    ports: 
      - ${BACKEND_MAP_PORT}:${BACKEND_SERVER_PORT}
    depends_on:
      - database

  gateway:
    build: ./gateway
    container_name: gateway
    command: python manage.py runserver ${GATEWAY_HOST}:${GATEWAY_SERVER_PORT}
    volumes: 
      - ./gateway:/gateway
    ports: 
      - ${GATEWAY_MAP_PORT}:${GATEWAY_SERVER_PORT}
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    command: ng serve --host 0.0.0.0 --port 32145
    volumes: 
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.angular
    ports: 
      - 4200:32145
    depends_on:
      - gateway
