version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver ${BACKEND_HOST}:${BACKEND_SERVER_PORT}
    volumes: 
      - ./backend:/backend
    ports: 
      - ${BACKEND_MAP_PORT}:${BACKEND_SERVER_PORT}
    depends_on:
      - database

  gateway:
    build: ./gateway
    container_name: gateway
    command: python manage.py runserver ${GATEWAY_HOST}:${GATEWAY_SERVER_PORT}
    volumes: 
      - ./gateway:/gateway
    ports: 
      - ${GATEWAY_MAP_PORT}:${GATEWAY_SERVER_PORT}
    depends_on:
      - backend
